# Lab | Data Aggregation and Filtering

In this challenge, we will continue to work with customer data from an insurance company. We will use the dataset called marketing_customer_analysis.csv, which can be found at the following link:

https://raw.githubusercontent.com/data-bootcamp-v4/data/main/marketing_customer_analysis.csv

This dataset contains information such as customer demographics, policy details, vehicle information, and the customer's response to the last marketing campaign. Our goal is to explore and analyze this data by first performing data cleaning, formatting, and structuring.

In [1]:
import numpy as np
import pandas as pd

In [2]:
url = "https://raw.githubusercontent.com/data-bootcamp-v4/data/main/marketing_customer_analysis.csv"
marketing_customer_analysis = pd.read_csv(url)
marketing_customer_analysis.head()

,Unnamed: 0,Customer,State,Customer Lifetime Value,Response,Coverage,Education,Effective To Date,EmploymentStatus,Gender,...,Number of Open Complaints,Number of Policies,Policy Type,Policy,Renew Offer Type,Sales Channel,Total Claim Amount,Vehicle Class,Vehicle Size,Vehicle Type
0,0,DK49336,Arizona,4809.216960,No,Basic,College,2/18/11,Employed,M,...,0.0,9,Corporate Auto,Corporate L3,Offer3,Agent,292.800000,Four-Door Car,Medsize,NaN
1,1,KX64629,California,2228.525238,No,Basic,College,1/18/11,Unemployed,F,...,0.0,1,Personal Auto,Personal L3,Offer4,Call Center,744.924331,Four-Door Car,Medsize,NaN
2,2,LZ68649,Washington,14947.917300,No,Basic,Bachelor,2/10/11,Employed,M,...,0.0,2,Personal Auto,Personal L3,Offer3,Call Center,480.000000,SUV,Medsize,A
3,3,XL78013,Oregon,22332.439460,Yes,Extended,College,1/11/11,Employed,M,...,0.0,2,Corporate Auto,Corporate L3,Offer2,Branch,484.013411,Four-Door Car,Medsize,A
4,4,QA50777,Oregon,9025.067525,No,Premium,Bachelor,1/17/11,Medical Leave,F,...,NaN,7,Personal Auto,Personal L2,Offer1,Branch,707.925645,Four-Door Car,Medsize,NaN

In [23]:
mkt_analysis_df = marketing_customer_analysis.copy()
mkt_analysis_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10910 entries, 0 to 10909
Data columns (total 26 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Unnamed: 0                     10910 non-null  int64
 1   Customer                       10910 non-null  object
 2   State                          10279 non-null  object
 3   Customer Lifetime Value        10910 non-null  float64
 4   Response                       10279 non-null  object
 5   Coverage                       10910 non-null  object
 6   Education                      10910 non-null  object
 7   Effective To Date              10910 non-null  object
 8   EmploymentStatus               10910 non-null  object
 9   Gender                         10910 non-null  object
 10  Income                         10910 non-null  int64
 11  Location Code                  10910 non-null  object
 12  Marital Status                 10910 non-null  object
 13  Monthly Premium Auto           10910 non-null  int64
 14  Months Since Last Claim        10277 non-null  float64
 15  Months Since Policy Inception  10910 non-null  int64
 16  Number of Open Complaints      10277 non-null  float64
 17  Number of Policies             10910 non-null  int64
 18  Policy Type                    10910 non-null  object
 19  Policy                         10910 non-null  object
 20  Renew Offer Type               10910 non-null  object
 21  Sales Channel                  10910 non-null  object
 22  Total Claim Amount             10910 non-null  float64
 23  Vehicle Class                  10288 non-null  object
 24  Vehicle Size                   10288 non-null  object
 25  Vehicle Type                   5428 non-null   object
dtypes: float64(4), int64(5), object(17)
memory usage: 2.2+ MB

In [27]:
mkt_analysis_df.columns = [column_name.lower().replace(" ", "_") for column_name in mkt_analysis_df.columns]

In [34]:
mkt_analysis_df.isna().sum()

unnamed:_0                          0
customer                            0
state                               0
customer_lifetime_value             0
response                            0
coverage                            0
education                           0
effective_to_date                   0
employmentstatus                    0
gender                              0
income                              0
location_code                       0
marital_status                      0
monthly_premium_auto                0
months_since_last_claim             0
months_since_policy_inception       0
number_of_open_complaints           0
number_of_policies                  0
policy_type                         0
policy                              0
renew_offer_type                    0
sales_channel                       0
total_claim_amount                  0
vehicle_class                     554
vehicle_size                      554
vehicle_type                     4865
dtype: int64

In [33]:
mkt_analysis_df = mkt_analysis_df.dropna(subset=["state", "months_since_last_claim" ])

1. Create a new DataFrame that only includes customers who:
   - have a **low total_claim_amount** (e.g., below $1,000),
   - have a response "Yes" to the last marketing campaign.

In [38]:
# total_claim_amount < 1000 FILTRAR VALORES DE LA COLUMNA EN UN NUEVO DF
clients_under_1k_df = mkt_analysis_df[
    (mkt_analysis_df["total_claim_amount"] < 1000) &
    (mkt_analysis_df["response"].str.lower() == "yes") ]
clients_under_1k_df.sample(5)

,unnamed:_0,customer,state,customer_lifetime_value,response,coverage,education,effective_to_date,employmentstatus,gender,...,number_of_open_complaints,number_of_policies,policy_type,policy,renew_offer_type,sales_channel,total_claim_amount,vehicle_class,vehicle_size,vehicle_type
1155,1155,CT84535,California,3885.456401,Yes,Premium,College,2/28/11,Unemployed,M,...,0.0,1,Personal Auto,Personal L3,Offer1,Branch,504.000000,Four-Door Car,Large,NaN
3558,3558,ST96866,Washington,3123.080994,Yes,Basic,Bachelor,2/19/11,Unemployed,M,...,4.0,1,Special Auto,Special L3,Offer1,Agent,960.115399,SUV,Large,A
7343,7343,TA34903,Oregon,5838.899150,Yes,Basic,High School or Below,1/6/11,Employed,M,...,0.0,4,Personal Auto,Personal L1,Offer2,Agent,281.295903,Four-Door Car,Large,NaN
7743,7743,CV49750,Arizona,21423.637230,Yes,Basic,Bachelor,1/3/11,Unemployed,M,...,0.0,2,Personal Auto,Personal L3,Offer2,Agent,312.000000,Two-Door Car,Medsize,NaN
9459,9459,NX11526,Arizona,2759.978287,Yes,Basic,Bachelor,1/3/11,Employed,M,...,0.0,1,Corporate Auto,Corporate L2,Offer2,Agent,331.200000,Two-Door Car,Medsize,A

2. Using the original Dataframe, analyze:
   - the average `monthly_premium` and/or customer lifetime value by `policy_type` and `gender` for customers who responded "Yes", and
   - compare these insights to `total_claim_amount` patterns, and discuss which segments appear most profitable or low-risk for the company.

In [49]:
mkt_analysis_yes_df = mkt_analysis_df[mkt_analysis_df["response"].str.lower() == "yes" ]
mkt_analysis_yes_df.head()

,unnamed:_0,customer,state,customer_lifetime_value,response,coverage,education,effective_to_date,employmentstatus,gender,...,number_of_open_complaints,number_of_policies,policy_type,policy,renew_offer_type,sales_channel,total_claim_amount,vehicle_class,vehicle_size,vehicle_type
3,3,XL78013,Oregon,22332.439460,Yes,Extended,College,1/11/11,Employed,M,...,0.0,2,Corporate Auto,Corporate L3,Offer2,Branch,484.013411,Four-Door Car,Medsize,A
8,8,FM55990,California,5989.773931,Yes,Premium,College,1/19/11,Employed,M,...,0.0,1,Personal Auto,Personal L1,Offer2,Branch,739.200000,Sports Car,Medsize,NaN
15,15,CW49887,California,4626.801093,Yes,Basic,Master,1/16/11,Employed,F,...,0.0,1,Special Auto,Special L1,Offer2,Branch,547.200000,SUV,Medsize,NaN
19,19,NJ54277,California,3746.751625,Yes,Extended,College,2/26/11,Employed,F,...,1.0,1,Personal Auto,Personal L2,Offer2,Call Center,19.575683,Two-Door Car,Large,A
27,27,MQ68407,Oregon,4376.363592,Yes,Premium,Bachelor,2/28/11,Employed,F,...,0.0,1,Personal Auto,Personal L3,Offer2,Agent,60.036683,Four-Door Car,Medsize,NaN

In [50]:
mkt_analysis_yes_df["monthly_premium_auto"].mean()

np.float64(94.39265129682997)

In [53]:
monthly_premium_gender = mkt_analysis_yes_df.pivot_table(
    values="monthly_premium_auto",       # the main information we want to display!
    index="policy_type",    # what becomes the rows
    columns="gender",     # what becomes the columns
)

monthly_premium_gender

gender                  F          M
policy_type
Corporate Auto  94.556962  91.646259
Personal Auto   99.225490  90.832677
Special Auto    93.088235  86.838710

In [52]:
monthly_premium_gender_ltv = mkt_analysis_yes_df.pivot_table(
    values="customer_lifetime_value",       # the main information we want to display!
    index="policy_type",    # what becomes the rows
    columns="gender",     # what becomes the columns
)

monthly_premium_gender_ltv

gender                    F            M
policy_type
Corporate Auto  7784.143776  7901.766731
Personal Auto   8421.116737  7454.123490
Special Auto    7858.855683  8431.232650

In [57]:
total_claim_inv = mkt_analysis_yes_df.pivot_table(
    values=["monthly_premium_auto","customer_lifetime_value", "total_claim_amount" ], 
    index="policy_type", 
    columns="gender",   
)

total_claim_inv

               customer_lifetime_value              monthly_premium_auto  \
gender                               F            M                    F
policy_type
Corporate Auto             7784.143776  7901.766731            94.556962
Personal Auto              8421.116737  7454.123490            99.225490
Special Auto               7858.855683  8431.232650            93.088235

                          total_claim_amount
gender                  M                  F           M
policy_type
Corporate Auto  91.646259         436.199389  409.690026
Personal Auto   90.832677         455.836305  455.464900
Special Auto    86.838710         457.294286  432.390133

3. Analyze the total number of customers who have policies in each state, and then filter the results to only include states where there are more than 500 customers.

In [67]:
customer_state = mkt_analysis_df.groupby("state").size()
customer_state = customer_state[customer_state > 1000]
customer_state

state
Arizona       1814
California    3346
Oregon        2754
dtype: int64

4. Find the maximum, minimum, and median customer lifetime value by education level and gender. Write your conclusions.

In [70]:
ltv_analyze = mkt_analysis_yes_df.pivot_table(
    values="customer_lifetime_value",
    index="education", 
    columns="gender",
    aggfunc = ["min", "max", "median" ]
)

ltv_analyze

                              min                        max               \
gender                          F            M             F            M
education
Bachelor              2248.449633  2300.691547  33473.349460  24127.50402
College               2004.350666  2393.915369  25807.063000  22332.43946
Doctor                2395.570000  2491.317024   6265.343299  12731.95161
High School or Below  2397.036098  2227.072755  41787.903430  12298.68630
Master                2574.020376  2551.226692  19160.989940  14435.67365

                           median
gender                          F            M
education
Bachelor              5282.587508  5548.031892
College               4869.802612  5989.773931
Doctor                4014.453113  5073.282126
High School or Below  6503.397049  6366.225775
Master                5096.673223  7133.646572

# College shows the lowers ltv
Doctor hase the owest maximimun ltv and fimale school the highest one
Master male shows the higher median so probably has higher rates and best target

## Bonus

5. The marketing team wants to analyze the number of policies sold by state and month. Present the data in a table where the months are arranged as columns and the states are arranged as rows.

6.  Display a new DataFrame that contains the number of policies sold by month, by state, for the top 3 states with the highest number of policies sold.

*Hint:*
- *To accomplish this, you will first need to group the data by state and month, then count the number of policies sold for each group. Afterwards, you will need to sort the data by the count of policies sold in descending order.*
- *Next, you will select the top 3 states with the highest number of policies sold.*
- *Finally, you will create a new DataFrame that contains the number of policies sold by month for each of the top 3 states.*

7. The marketing team wants to analyze the effect of different marketing channels on the customer response rate.

Hint: You can use melt to unpivot the data and create a table that shows the customer response rate (those who responded "Yes") by marketing channel.

External Resources for Data Filtering: https://towardsdatascience.com/filtering-data-frames-in-pandas-b570b1f834b9

In [ ]:
# your code goes here